name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ghirahim_rs_build
    - name: Pull twitch-irc v4.0.0
      uses: actions/checkout@v2
      with:
        repository: robotty/twitch-irc-rs
        ref: 0cdb0d7d94f8991f47b584d6aa1a9ea46b1cee27
        path: twitch-irc-rs
    - name: Test
      run: cd ghirahim_rs_build && cargo test --verbose
    - name: Build
      run: cd ghirahim_rs_build && cargo build --verbose
