name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Upload build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ghirahim_bot
        path: target/release/ghirahim_bot
        if-no-files-found: error
